### ISSUE TITLE
Persistence there, but not working

### ISSUE THREAD

**Issue by GunnarAnderson** [SevenBits/Mac-Linux-USB-Loader#38]
Hi, so far everything is working great, except for the persistence. I followed the steps to make the file, and enterprise recognized it, and I was able to boot. So to test it I created a document, wrote gibberish, saved, and restarted. When I boot up again, the file wasn't there, the persistence did not work. I am using an 8gb flash drive, ubuntu 13.04, and the persistence file I created was 2gb. Did I do something wrong?

**Comment by SevenBits** [comment]
@GunnarAnderson @HyShai Try the persistence feature now included in Mac Linux USB Loader 3.0.

**Comment by HyShai** [comment]
@SevenBits The Target USB dropdown is always empty - so I'm not able to test it :(
![untitled copy](https://cloud.githubusercontent.com/assets/1154806/6055491/11e081e4-acce-11e4-889e-084cc8db1651.jpg)

**Comment by SevenBits** [comment]
@HyShai Is your USB drive formatted as FAT? Please see [here](https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/Frequently-Asked-Questions#3-why-isnt-my-usb-drive-detected-it-should-be-formatted-as-fat).

**Comment by HyShai** [comment]
@SevenBits yes it's formatted as FAT

**Comment by simplegreen23** [comment]
I was able to get persistence working with Kali 1.1.0a 64bit
I had another linux machine to use GParted
First un mount your linux usb drive
Then I resized linux partition down
With the unallocated space I made a new partition labeled as persistence
Formated as ext4
Applied Settings
Once the process is complete, mount your persistence USB partition using the following commands:
Note: Your usb drive could be in a different path. So make sure of that. Use GParted for reference.
mkdir /mnt/usb
mount /dev/sdb2 /mnt/usb
echo ”/ union” >> /mnt/usb/persistence.conf
umount /mnt/usb
Then I edited enterprise.cfg with textedit on another machine.
I just added the word persistence after the hostname and saved.
Thats it. Should boot with persistence every time. No need to select persistence mode in Kernel Options.
Hope this helps

**Comment by lyricalpolymath** [comment]
Hi @SevenBits (first, thanks for the great software)
I've followed your steps, plus a couple of things, but it still doesn´t work

**Steps I had to add**
when running
`mount /dev/sdb2 /mnt/usb`
I had a "Permission Denied" so I had to `sudo chmod 777 /mnt/usb`

**the problem is that resizing and formatting the "persistence" partition to ext4 made the whole USB key unreadable to mac, so it wasn't even recognised when booting with the option key (as it was before doing the whole GParted resizing+adding and renaming a new partition)***

I also tried the following hostname configurations before discovering that the problem was elsewhere.
```
hostname=Kali   	( default config generated by Mac Linux USB Loader)
hostname=persistence      	                
hostname=Kali persistence	                    
hostname=Kali hostname=persistence	
```

I've been using the Kali distro downloaded through your Mac Linux USB Loader (Kali 1.1.0a 64bit), and followed all your steps
Any idea about why this isn't working?
thanks in advance

**Comment by SevenBits** [comment]
@lyricalpolymath Did you try it using the built-in Mac Linux USB Loader persistence creation tool, or did you do something else, like the [old instructions on the Wiki page](https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/Using-Persistence-with-Mac-Linux-USB-Loader)?

**Comment by lyricalpolymath** [comment]
sorry I forgot to mention @simplegreen23 in my previous message

@SevenBits I used the built-in Mac Linux USB Loader persistence creation tool (version 3.1 9048)
but it was giving me some problems (slider not working, can´t input anything greater than 128MB - I'm using a 4Gb Usb). But When I clicked Create Persistence it did correctly create the casper-rw file besides the efi folder. (I've also booted every time with the (5) persistence boot option selected)
*Should one delete the casper-rw file after doing the steps explained by @simplegreen23 here in the github issue?

I think I must have done something wrong following @simplegreen23 instructions (`mount /dev/sdb2 /mnt/usb`) though because now, in Mac > Disk Utility, I can see the Kali startup partition but it has 2 problems:
1- it is not named "Kali" like I see in Gparted but it is called "disk1s1"
2- I can´t mount it on mac anymore

**What I've done is:**
1- format the whole USB as FAT32 with a MBR scheme
2- use MacLinux-USB-Loader > Setup USB Device > Enable Startup Disk Support
3- MacLinux-USB-Loader > Distribution Downloader (I will now try to install directly with the already downloaded .iso)
4- Waited for the the download and installation process
5- tested it and discovered there was no persistence
6- used MacLinux-USB-Loader > Persistence Manager  and created the casper-rw file on the key, although I had the problems described earlier one (128Mb limit + slider not working)
7- since the persistence didn't work, I looked up this issue and tried @simplegreen23 solution explained earlier, but didn't work either, as explained earlier 

I'll try restarting from scratch,
* **Are there instructions on how to use the built-in Mac Linux USB Loader persistence creation tool?**
* **Should I try to compile the latest version of MacLinux-USB-Loader?**

**Comment by ricoshe81** [comment]
Same problem here with kali 2.0

**Comment by SevenBits** [comment]
@lyricalpolymath @ricoshe81 The persistence feature currently only works on Ubuntu. I am working on support for other Linux distributions.

**Comment by lyricalpolymath** [comment]
ok thanks

**Comment by Ezachiel** [comment]
[quote=simplegreen23]I was able to get persistence working with Kali 1.1.0a 64bit
I had another linux machine to use GParted
First un mount your linux usb drive
Then I resized linux partition down
With the unallocated space I made a new partition labeled as persistence
Formated as ext4
Applied Settings
Once the process is complete, mount your persistence USB partition using the following commands:
Note: Your usb drive could be in a different path. So make sure of that. Use GParted for reference.
mkdir /mnt/usb
mount /dev/sdb2 /mnt/usb
echo ”/ union” >> /mnt/usb/persistence.conf
umount /mnt/usb
Then I edited enterprise.cfg with textedit on another machine.
I just added the word persistence after the hostname and saved.
Thats it. Should boot with persistence every time. No need to select persistence mode in Kernel Options.
Hope this helps[/quote]

This method is working for me currently with KALI 2.0 using a mbp.

Thanks  simplegreen23.

**Comment by garynunes** [comment]
Thanks for Mac Linux USB Loader. Very useful.

Having created a Ubuntu persistent bootable USB drive using your software I'd like to point out two "rough" areas I ran into during the process:

First (as mentioned in previous posts),initially the persistent creating dialog didn't seem to work. Sliding the slider doesn't change the readout in the size field and the size field itself isn't editable (i.e., you can select it but not type into it). As I learned through experimentation changing the slider does change the size of the created persistent area ... there is just no indication in the dialog that anything is happening (you just have to estimate the size based on slider position). I imagine fixing that won't be too much of a problem.

Second, at first I didn't think persistency worked at all. It took a while (i.e., some searching) to discover that I needed to boot through the "Advanced" menu rather than directly. Also, the (eventually) found instructions say press 2 (advanced), 5 (persistence), 0 (boot) whereas there's no need to press 5 unless that option is not highlighted (which, at least for me, it was highlighted by default). Also, it wasn't initially clear that, in order for persistence to ... well ... persist you must always boot through the Advanced menu. Perhaps just a bit of documentation cleanup?

Anyway, after some trial and error, it all works ... so thanks again.

**Comment by SevenBits** [comment]
@garynunes Thank for your suggestions. I will take them into consideration for the next release.

**Comment by ashwanijha04** [comment]
I am trying to boot kali linux from my external hard disk. I created a persistence.conf file and also tried using mac linux usb loader to create persistence. When I go to advanced boot options, select 5 and 0. The persistence just doesn't work. Is there a way to use persistence for kali linux when booting from an external hard drive to a mac? Also, please help me with the wifi drivers, they just don't show up.
