### ISSUE TITLE
Can't login to Kali

### ISSUE THREAD

**Issue by Addisonbean** [SevenBits/Mac-Linux-USB-Loader#48]
I recently download v2.0 of this app, and create a Kali USB to boot with. It all works fine until the login section. It asks for a username and password, but I never set one. And I tried the default user/pass root, and toor and that didn't work either. Does this app make it's own default login info? It never asked me to install or setup anything when I booted up with the USB.

**Comment by Gairlochan** [comment]
Hello SevenBits,
I'm not sure if this is the right place to post a problem I've been having with booting from flash drive made with Mac-Linux-USB-Loader, but I hope so.

MLUL runs fine and instals the .iso file on the flash drive; so far so good. It's when I try booting my Mac Pro (with ReFind installed) or my Macbook Pro (without ReFind) from it that the problem occurs. It gets a little way into booting and, with a black screen, gives me this message … 

kernel path: /casper/vmlinuz | ramdisc path: /casper/initrd.lsboot parameters:
Loading Linux kernel…done
Loading initial RAM disc…done
Attempting to boot the Linux distribution now…
error: no suitable video mode found.
Booting in blind mode

… and there it stops.

This happens over and over again, both with my 2009 Mac Pro (with standard 24" Apple monitor) and my 2008 Macbook Pro. I have tried several different distros, including Ubuntu, Mint and Elementary. I can, and do, run several distros within VMWare Fusion virtual machines, and they work fine. But I would really like to get at least one installed 'properly'.

Lachlan

**Comment by SevenBits** [comment]
@Gairlochan Are you trying to load Ubuntu? You neglected to say which distribution you are trying to load.

The "booting in blind mode" error has been resolved as of Mac Linux USB Loader v3.0, released on Christmas Eve. Which version are you using?

**Comment by Gairlochan** [comment]
In the last paragraph of my post I mentioned some of the distros I've tried (Ubuntu, Mint and Elementary). There have been several others, but I can't recall which ones now. I get the same results with all distros I've tried. I've been using v2, but I'll try v3 and let you know whether it works better or not.

Btw, would a live USB flash drive boot up a late model Windows box? I want to put one together for my son, a long-time Mac user who's recently become a Micro$lave (because the hardware is cheaper), in an attempt to get him onto something healthier than M$Windows.

**Comment by SevenBits** [comment]
@Gairlochan Please use Mac Linux USB Loader version 3.0. It has many fixes, especially for Ubuntu.

Live USB sticks created by this tool *may* be able to load on PCs if that PC is based on UEFI. See my answer to this in the Frequently Asked Questions page [here](https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/Frequently-Asked-Questions#1-does-mac-linux-usb-loader-support-uefi-based-pcs).

**Comment by Gairlochan** [comment]
Hello SevenBits,

I’ve lost the link to the blog page, and found it Impossible to find again, So I’ll answer  your question here to the best of my ability to remember it:

 You ask if I had downloaded version 3, and what results I have had with it. I did download it, and have had mixed results with it but still have been unable to boot completely into any of the Linux versions that I’ve tried (Elementary, Mint, Ubuntu and Fedora), with pretty much the same lack of success on my Mac Pro (with ReFind) and my MacBook Pro (without ReFind).

I’ve been able to get past that ‘booting into blind mode’ error message, and even past grub, but as soon as I get into the ‘booting into Linux now’ part of the process it crashes repeatedly, and I can’t get past that stage. I had thought that Fedora would be better than the others after reading that it seemed to have better success in booting up a Mac, but it was in fact worse than the others.

Do you have any suggestions as to what I might try next?

 Regards, Lachlan

PS: thank you for the time you've spent trying to help me. I do appreciate it.

**Comment by SevenBits** [comment]
@Gairlochan Ubuntu has been confirmed to work with Mac Linux USB Loader version 3.0 and above. If it does not work for you, please try adjusting the Linux boot options; it could be a hardware incompatibility. Without knowing more about your specific configuration I unfortunately cannot say more.

**Comment by SevenBits** [comment]
@kalihack2014 @Addisonbean @Soap109 If anyone is waiting for a progress report on Kali, you'll be happy to see these photos.

![img_5474](https://cloud.githubusercontent.com/assets/2482736/6982863/56045cf8-d9e5-11e4-9d57-5ca8817cee9a.JPG)
![img_5475](https://cloud.githubusercontent.com/assets/2482736/6982866/5a05f942-d9e5-11e4-99b9-c7905aad7f99.JPG)

You'll have to wait for Mac Linux USB Loader 3.1, though...

**Comment by Addisonbean** [comment]
Awesome thanks! Can't wait

**Comment by dastefster** [comment]
:D ^^^^ I'm a relatively new Kali user (with a mac) and I spent HOURS trying to successfully create and boot it from a USB with persistence....no luck. Followed instructions on Kali's docs website, numerous other youtube videos, and even the Enterprise instructions combined with your program (usb loader) but still the furthest i've gotten is selecting the disk from the rEFInd recovery start-up menu, it begins to load but then just hangs forever saying "unable to locate controller" in the top left :( Love the USB loader program though! It create live bootable USB's for all of the other Linux-based systems (e.g: Ubuntu) I've tried except Kali! The one I want, of course lol. Any expected release date for 3.1?? Is there a beta? @SevenBits

**Comment by SevenBits** [comment]
@dastefster A beta should come soon, followed at some point in the future with the final release. There are a few kinks I need to work out before I feel comfortable releasing the beta, though. If you really want to try it now, you can compile the source code.

But I do need to ask which options you used to configure Enterprise to boot Kali. If you look on the Enterprise website, you'll see a configuration file for a working configuration; you just need to set up the rest of Enterprise correctly and it should just work.

**Comment by dastefster** [comment]
@SevenBits well is it functional at all? Are the "kinks" just little bugs that make the UI annoying or crash it? I'd love to/be happy to help! If you'd like, but what do you work with? Python? I'm not sure exactly what you need/want written, but I'm far from a pro. I've done some HTML & Java stuff but never like designed a entire computer program haha. Although, it does sound interesting/fun. 

Here is exactly what I did: 
-Downloaded Enterprise 0.2.1 binaries from Enterprise site
-created: /efi/boot/.MLUL-Live-USB plain text file in my USB drive (formatted in MS-DOS (FAT16))
- .MLUL-Live-USB file contained: 
entry Kali
family Debian
iso kali.iso
kernel /live/vmlinuz findiso=/efi/boot/boot.iso boot=live noconfig=sudo username=root hostname=kali

Thats how I configured it. When I tried to boot it said something like "controller not found" in the top left and just hung there for maybe 5 minutes until I just forced shut down and restarted with my OS X drive. Did I make a mistake? 

Also, side note: I tried to run the USB with that^ file BEFORE installing rEFInd, because I was thinking/hoping I would not need it. Then when it did not work I figured I'd try installing rEFInd, even though the Kali docs site says newer macs should not have to. It didn't work that time either, but I think I may have messed up the rEFInd install/setup because now when I turn my computer off and restart it holding 'option' it just takes me to the native os x start up disk selector BUT if I just start my computer normally (not holding option) the rEFInd boot manager comes up! Probably going to try to remove it and re-install from scratch more carefully, unless you have another suggestion? Thanks!

**Comment by SevenBits** [comment]
@dastefster Your setup looks okay, but there's a bug in Kali's kernel making the display not work. The "controller not found" message is something else and is probably not related to this issue. The screenshots that you saw were from a newer build of Kali (from a private server which the Kali developers let me access). It fixes some of these issues; I will see if I can share the link to the working ISO with everyone.

Again, rEFInd is **not** needed. Your setup should work just fine -- the bugs are related to Kali, not to Mac Linux USB Loader.

**Comment by dastefster** [comment]
@SevenBits oh that'd be sweet! So funny/weird story: after many failed attempts and trying different configurations/methods/ideas last night, I actually got it to boot and run live from my USB! The weird part is how; so the very first time I tried to make/boot a Kali live usb I was following the instructions from their docs site, which didn't work. That's how/why I found your app. Long story short, after a lot of brainstorming and comparing the different road blocks I was running into using they're instructions vs yours I thought of a way to take the "working" parts from both and combine them. USB loader seemed to be having an issue with the executable files it installed communicating with Kali and I figured the problem I was having with the "kali method" had to do with the boot manager. Whether I was right or wrong, I got it to work by first moving the .iso file to a .img, which OS X seems to play better with. Then I moved it to my USB using dd in Terminal and once it was finished I went into the /boot file, deleted the existing .MLUL .exec and replaced it with the one I made following the Enterprise instructions. Booted like a charm. Although, I still would like to do it via USB Loader because I'm now trying to manually configure a persistence partition in kali's root terminal...it has not been an easy task thus far.

**Comment by SevenBits** [comment]
@dastefster @Addisonbean @kalihack2014 @evilninjection A beta of Mac Linux USB Loader version 3.1 is out. Head over to the releases page to grab it.

**Comment by baishakh22** [comment]
In the MacBook, I'm using an M1 chip. After I install my Kali in my VMWare Fusion it runs pretty well. Then after I went to dinner. I just saw my kali Linux is logged out. I tried my laptop password and so other stuff. Like admit, root and and so on. Then it works with "kali"
