### ISSUE TITLE
KaliLinux boots right up, doesn't give choice to choose "live"

### ISSUE THREAD

**Issue by Lucurus** [SevenBits/Mac-Linux-USB-Loader#91]
Hi,

first of all thanks for this amazing piece of software. 
I just have one question.

I can't choose the available building options (Live, live with persistence, install,...). Every time I boot from a flash drive, it starts the full OS without giving me any choice to choose what kind of build I want.

I installed Kali 2.0 64 bit (downloaded from the official website) and put it on a SanDisk extreme flash drive. I did all this on an iMac 27" 5K running OSX 10.11.1. I then plugged the flash drive into my MacBookPro Retina (middle 2015) which runs on 10.11.1 as well. When I booted my MacBook up, I pressed the "alt"-key and it showed me the "EFI-Boot"-drive. I chose the drive and the boot option "1)" (Boot Linux from ISO-file. It then boots right into the OS without showing any boot option such as the live-build option.

Is this not possible with the USB-Loader or is this an error?

Thanks for your help.
Cheers

**Comment by SevenBits** [comment]
Sigh... according to the [contribution rules](https://github.com/SevenBits/Mac-Linux-USB-Loader/blob/master/CONTRIBUTING.md) this should be posted on [SevenBits/Enterprise](https://github.com/SevenBits/Enterprise/issues)...

Mac Linux USB Loader bypasses the boot options programmed by the distribution. This is because these options more often than not do not work with Enterprise, Mac Linux USB Loader's boot loader, and because they are usually not set up to permit booting from ISO, which Mac Linux USB Loader requires.
